name: TFLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**.tf'
      - '.tflint.hcl'
      - '.github/workflows/tflint.yml'

jobs:
  tflint:
    name: TFLint Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        name: Checkout source code

      - uses: actions/cache@v5
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint (Root)
        working-directory: terraform
        run: tflint -f compact

      - name: Run TFLint (Examples)
        run: tflint -f compact
        working-directory: terraform/examples/complete
